name: Spec Delta
description: Generate cURL examples from OpenAPI diff
author: Saizad
branding:
  icon: terminal
  color: blue
inputs:
  openapi:
    description: Path to OpenAPI spec file
    required: true
  diff:
    description: Path to API diff file
    required: true
  outdir:
    description: Output directory for cURL files
    required: false
    default: curl-diff-out
  markdown_outdir:
    description: Output directory for markdown files (if not provided, markdown generation is skipped)
    required: false
  github_url:
    description: Base GitHub URL for endpoint hyperlinks (e.g., 'https://github.com/user/repo/blob')
    required: false
  branch:
    description: GitHub branch name for hyperlinks (default -- main)
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate && pip install --upgrade pip && pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash
    - name: Run Spec Delta generator
      run: |
        . venv/bin/activate && python "${{ github.action_path }}/generator.py" "${{ inputs.openapi }}" "${{ inputs.diff }}" -o "${{ inputs.outdir }}"
      shell: bash
    - name: Generate markdown from diff output
      if: ${{ inputs.markdown_outdir != '' }}
      run: |
        . venv/bin/activate && python "${{ github.action_path }}/log_markdown_convertor.py" "${{ inputs.outdir }}" "${{ inputs.markdown_outdir }}"
      shell: bash
    - name: Generate Readme from diff output
      run: |
        . venv/bin/activate
        GITHUB_ARGS=""
        if [ -n "${{ inputs.github_url }}" ]; then
          GITHUB_ARGS="--github-url '${{ inputs.github_url }}'"
        fi
        if [ -n "${{ inputs.branch }}" ]; then
          GITHUB_ARGS="$GITHUB_ARGS --branch '${{ inputs.branch }}'"
        fi
        python "${{ github.action_path }}/summary_markdown_convertor.py" "${{ inputs.outdir }}/summary.txt" -o "${{ inputs.outdir }}/README.md" $GITHUB_ARGS
      shell: bash